api_version = "2025-01"

[[extensions]]
name = "OptionForge Cart Transform"
handle = "cart-transform"
uid = "723515e5-bc2e-45c6-6942-564c29099db8e998c0bc"
type = "function"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = "npm run build --workspace=cart-transform"
  path = "dist/function.js"
  watch = ["src/**/*.js", "src/**/*.graphql"]

  [extensions.ui.paths]
  create = "/cart-transforms/new"
  details = "/cart-transforms/:id"
