client_id = "REPLACE_WITH_YOUR_CLIENT_ID"
name = "optionforge"
handle = "optionforge"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/updated"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"

  [[webhooks.subscriptions]]
  topics = [ "themes/publish" ]
  uri = "/webhooks/themes/publish"

[access_scopes]
scopes = "read_products,write_products,read_product_listings,read_orders,read_all_orders,read_themes,write_themes,read_files,write_files,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,write_cart_transforms,read_translations,write_translations,read_locales,read_markets"
optional_scopes = [ "read_customers" ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://example.com/proxy"
subpath = "optionforge"
prefix = "apps"
